### ISSUE TITLE
Update Advanced Recruit Training

### ISSUE THREAD

**Issue by bill-luu** [UCSolarCarTeam/Recruit-Resources#50]
Let's update this too:

- Re-structure the program so that the files are in a similar system such as the other projects on the team (eg. Have Layers)

- Add to the README: how the calculations are done. I don't think that needing to know how Amphours are calculated is that important, irl that info would be a datasheet or given by the electrical team.

- Add in a GUI component.

**Comment by enochtsang** [comment]
I think for the first poitn, there's not enough files to condone a layer system. The advanced recruit training is still one step towards production code, not mimicking. With that, I don't think a GUI component is necessary either.

**Comment by bill-luu** [comment]
You do have a point on the amount of files, but I think there should be some kind of GUI component, that's been one of the biggest difficulties new recruits have been having on working with QT. Although it might not work on how it's set right now, maybe we can add in something simple like "Display the time the highest voltage is". And if we do have a GUI part then we might have enough to do a rough layering.
